# fly.toml app configuration file generated for rsomhap on 2024-08-22T01:06:04+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rsomhap"
primary_region = "nrt"

[http_service]
auto_start_machines = true
auto_stop_machines = "suspend"
force_https = true
internal_port = 5_299
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/ping"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"
