# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy to Fly.io

on:
  workflow_run:
    workflows:
      - Test with Neon Branch
    types:
      - completed
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy app
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    concurrency:
      group: deploy
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Install fly
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> "$GITHUB_PATH"
      - name: Set secrets
        run: fly secrets set --stage DATABASE_URL="${DATABASE_URL}" UMAMI_ID="${UMAMI_ID}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          UMAMI_ID: ${{ secrets.UMAMI_ID }}
      - name: Deploy
        run: fly deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
